### ISSUE TITLE
Uncaught ReferenceError: PWA_CONFIG is not defined

### ISSUE THREAD

**Issue by TehEbil** [jfadev/jfa-pwa-toolkit#10]
Hi, I followed the tutorial. At first, I put the pwa folder inside some other folders, next to index.html. But it didn't work, so I moved the folder to the root.

Unfortunately, it still gives me the same error:
```
sw.js:19 Uncaught ReferenceError: PWA_CONFIG is not defined
    at sw.js:19
(anonymous) @ sw.js:19
pwa.js:32 PWA: Service Worker registration failed with TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed
```

Do you know why? It seems that all the files do not share the global namespace. The file get loaded (I tested it with a console.log in config.js), but other files cannot read it. I use it on an angularjs app.

Also, it seems that PWA_ROOT definition is missing

**Comment by jfadev** [comment]
Hello,
You are grouping all js files with webpack or similar?

Think that the `config.js` file must be accessible from both `window` and
from the `service worker`.
Due to its error, the global constant `PWA_CONFIG` does not exist.

Try to keep the original structure:

/index.html
/sw.js
/pwa/

(But you should check if all paths are correct in the project)

Load scripts in classic mode:
```
<script type="text/javascript" src="/pwa/config.js"></script>
<script type="text/javascript" src="/pwa/pwa.js"></script>
/* Your angular app */
<script type="text/javascript" src="/public/app.js"></script>
```
You can also clone this functional demo:
https://github.com/jfadev/jfa-pwa-toolkit-demo

At the moment I am working on the [dev](https://github.com/jfadev/jfa-pwa-toolkit/tree/dev) branch that will be an NPM package and can be used much more easily in modern js frameworks.
I hope to finish it soon 😁

**Comment by TehEbil** [comment]
Hi, thank you very much for your fast response!

I do not group those files (none at all), I just include them as is (as you shown, these three are just the last scripts called (and also PWA.ServiceWorker.register();)). I have same paths and all files are included correcty. The only difference is index, index is in
```
/theme/index.html
/pwa
/sw.js
```

Might there be something else which disables global variables somehow?

And sorry if offtopic - I always upload these to production server, because of ssl_certificate errors. Do you test these actually on your local machine? I tried some tutorials, but none of them actually worked :x

**Comment by jfadev** [comment]
In general, you need to serve both your page and your service worker script 
via `HTTPS` in order to use service workers. 

There is an exception to the HTTPS requirement to facilitate local development:
if you access your page and the service worker script
via` http://localhost[:port]`, or via `http://127.x.y.z[:port]`,
then service workers should be enabled without any other action.

How do you get your index.html? 
from `http://localhost/` or `http://localhost/theme/` ?

The following files should be published in the following URLs so you don't have to change anything:

http://localhost/sw.js
http://localhost/pwa/config.js
http://localhost/pwa/pwa.js
http://localhost/pwa/manifest.json
or
https://yourdomain.com/sw.js
https://yourdomain.com/pwa/config.js
https://yourdomain.com/pwa/pwa.js
https://yourdomain.com/pwa/manifest.json

you need the following code in all your pages: ex:
https://yourdomain.com/
https://yourdomain.com/news/
https://yourdomain.com/about/

```
<html>
<head>
    <link rel="manifest" href="/pwa/manifest.json"></link>
    <!-- ... -->
</head>
<body>
    <!-- ... -->
    <script type="text/javascript" src="/pwa/config.js"></script>
    <script type="text/javascript" src="/pwa/pwa.js"></script>
    <script type="text/javascript">
        PWA.ServiceWorker.register();
    </script>
</body>
</html>
```

Try running your project at `http://localhost/` and make sure that your service worker has been loaded correctly in `DevTools>Application>Service Workers`

If you still have problems, do not hesitate to keep asking here until we make it work. 👍
